// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdxbeWeIQdK0G9R4Tz-B_Nxb7T-yq8ho',
    appId: '1:185986787184:web:9ddd604a02c7015d6091b5',
    messagingSenderId: '185986787184',
    projectId: 'flutter-6cd7f',
    authDomain: 'flutter-6cd7f.firebaseapp.com',
    databaseURL: 'https://flutter-6cd7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-6cd7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_qLcJla2YO9KpWT7JD6pZB7n3GOvcYM',
    appId: '1:185986787184:android:efda782e6b963c7f6091b5',
    messagingSenderId: '185986787184',
    projectId: 'flutter-6cd7f',
    databaseURL: 'https://flutter-6cd7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-6cd7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZ2bqhdjoaejlXUxcId_Wl0FWfXdSAj0',
    appId: '1:185986787184:ios:657ab5ac256c18156091b5',
    messagingSenderId: '185986787184',
    projectId: 'flutter-6cd7f',
    databaseURL: 'https://flutter-6cd7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-6cd7f.appspot.com',
    iosClientId: '185986787184-6milh6841vrl64jq5k4lujrhtse2v7en.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZ2bqhdjoaejlXUxcId_Wl0FWfXdSAj0',
    appId: '1:185986787184:ios:657ab5ac256c18156091b5',
    messagingSenderId: '185986787184',
    projectId: 'flutter-6cd7f',
    databaseURL: 'https://flutter-6cd7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-6cd7f.appspot.com',
    iosClientId: '185986787184-6milh6841vrl64jq5k4lujrhtse2v7en.apps.googleusercontent.com',
    iosBundleId: 'com.example.logindb',
  );
}
